version: '2'
services:
  authentication-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/authentication/postgresql/:/var/lib/authentication/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - POSTGRES_DB=authentication
    ports:
      - 8988:5432
